# Generated by Django 4.1.3 on 2022-11-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_validation', '0002_otp_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='username',
        ),
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
