# Generated by Django 4.1.3 on 2022-12-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_validation', '0004_otp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='date',
            field=models.TimeField(null=True),
        ),
    ]
